# Window dimensions
width: 1280
height: 720

# V-sync enabling flag. If true, framerateLimit is ignored
# V-sync is recommended to avoid screen tearing, but with some Linux graphics drivers it will
# make the update loop run at 100% CPU.
vsync: false

# Framerate limit
framerateLimit: 60

# Anti-aliasing level (0 for no anti-aliasing)
antialiasingLevel: 0

# Window title
title: "C++ Platform Adventure"
